name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  laravel-ci:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: cp ../.env .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Directory Permissions
      run: chmod -R 777 storage storage
    - name: Database Migration
      run: php artisan migrate --force
